name: ci

on:
  workflow_dispatch:
  pull_request:
    branches:
        - c4t
        - dev
env:
  docker_image: "c4tplatform/camino-conduit"

jobs:
  build_docker:    
    name: Build Docker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ env.docker_image }}:temp
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true


      - name: Verify image
        run: |
          docker run --rm ${{ env.docker_image }}:temp --version
  
  build_binary:    
    name: Build Binary
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: build binary
        run: |
          ./scripts/build.sh
          ./build/camino-conduit --version