name: Release

on:
  release:
    types: [published]

env:
  docker_image: "c4tplatform/camino-conduit"

jobs:
  build_docker:    
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.docker_image }}:latest
            ${{ env.docker_image }}:${{ github.event.release.tag_name }}